github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
title: 40k History
exclude:
  - .idea
  -  start.sh
collections:
  units:
    output: true
    permalink: /units/:categories/:title.html
  rules:
    output: true
    permalink: /rules/:categories/:title.html
  weapons:
    output: true
    permalink: /weapons/:categories/:title.html
  models:
    output: true
    permalink: /models/:categories/:title.html
