github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
title: 40k History
exclude:
  - .idea
  -  start.sh
collections:
  units:
    output: true
    permalink: /:categories/units/:title.html
  rules:
    output: true
    permalink: /:categories/rules/:title.html
  weapons:
    output: true
    permalink: /:categories/weapons/:title.html
  models:
    output: true
    permalink: /:categories/models/:title.html
  editions:
    output: true
    permalink: /:title.html
  sources:
    output: true
    permalink: /:categories/sources/:title.html